name: Docker Image CI with cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, tag, and push image to Amazon ECR
        uses: whoan/docker-build-with-cache-action@v5
        with:
          push_image_and_stages: false
          image_name: test_repo
